### ISSUE TITLE
Add option to gracefully catch errors on individual import item requests

### ISSUE THREAD

**Issue by nkooman-bzs** [kontent-ai/kontent-ai-migration-toolkit#10]
### Motivation

When doing larger migrations sometimes it would be more ideal to let the import continue rather than fail entirely and report afterward that there are items that failed.
For example, I do not want the entire process to fail when an item is not able to be published due to missing elements. I would rather see the publish fail and for the process to continue.

### Proposed solution

Add an option to continue on failure, adding a catch statement in [`processing-utils.ts`](https://github.com/kontent-ai/kontent-ai-migration-toolkit/blob/40b50d53d1ff27d66cb197a6297ee1d2ee717228/lib/core/utils/processing-utils.ts#L37). Here we could check for a flag to determine whether we re-throw the error.
Potentially offer the ability to set a function that will run when an item fails. That way a user can easily inject external logic or logging when a failure happens.

### Additional context

N/A

**Comment by Enngage** [comment]
Will be implemented as a part of - https://github.com/kontent-ai/kontent-ai-migration-toolkit/pull/21
