### ISSUE TITLE
Handle workflow transition restrictions

### ISSUE THREAD

**Issue by nkooman-bzs** [kontent-ai/kontent-ai-migration-toolkit#13]
### Motivation

I have a published item with an advanced workflow that I am trying to migrate.
The default draft state of the workflow cannot transition to published and fails when the migration toolkit attempts to do so.
For example a linear translation workflow:
- Ready to Translate
- Translation in Progress
- Ready for Review
- Published

### Proposed solution

Retrieve all the workflows from the target environment and dynamically construct workflow step updates to properly set an item's workflow step.

### Additional context

N/A

**Comment by nkooman-bzs** [comment]
@Enngage I have some changes I've been working on to resolve this issue. I can create a draft PR as a starting point. In my testing it's working, but I'd like some extra eyes on it.

**Comment by Enngage** [comment]
Thank you very much @nkooman-bzs  :) Though, it seems the PR might not be required after all because my colleague told me he was already working on this, but haven't pushed it to GH just yet.

**Comment by Enngage** [comment]
This has now been implemented and merged to main ;)
