### ISSUE TITLE
Import Script Failing completely for an invalid item.

### ISSUE THREAD

**Issue by subhamAgarwal-cloud** [kontent-ai/kontent-ai-migration-toolkit#18]
### Brief bug description

Hi team, 
I was doing data migration from excel sheet to Kontent Ai. for a content model using the Migration Toolkit.  

What went wrong?
I encountered an issue that the content item name cannot be more than 200 characters. The issue is understood that the Kontent AI had some limitations on the content item name. But the migration script stopped importing the items. I believe this should not happen and it should move to next item skipping the item which has errors. I was importing around 67005 items and it failed after 11 hours just because some items had a content item name greater than 200 characters. 

### Repro steps

None.

### Expected behavior

The script should still keep on importing the items and skip the invalid items and log it .  

What is the correct behavior?

The script should still keep on importing the items and skip the invalid items and log it .  

### Test environment

 Kontent Ai - UAT environment of a project.

### Additional context

--------------------------

### Screenshots

error screenshots

![Error](https://github.com/user-attachments/assets/3c4a9ca7-8595-40c7-aec9-2d543df6596b)

Migration script Screenshot
![MigrationSS-1](https://github.com/user-attachments/assets/49131fbc-13cd-4a29-a14f-d4360ddd1c92)
![MigrationSS-2](https://github.com/user-attachments/assets/b1145e36-e001-462c-9f73-c2ad04791237)
![MigrationSS-3](https://github.com/user-attachments/assets/4bc738a3-ec2f-474e-8ed8-b6ee4286c1c0)
![MigrationSS-4](https://github.com/user-attachments/assets/3efe6726-5943-4727-a354-1853e19ab43d)
![MigrationSS-5](https://github.com/user-attachments/assets/18e9cecd-7be8-48c3-8ec3-9c3963b66ad5)
![MigrationSS-6](https://github.com/user-attachments/assets/c5ce1ad8-551d-4ec9-b4b5-cb5a16b3e808)

**Comment by IvanKiral** [comment]
Hey @subhamAgarwal-cloud. I'm sorry for not getting back to you sooner, and thanks for the issue.

the migrations aren't rolled back after the migration toolkit fails, so you can also skip the item that was not able to migrate. That being said, being able to skip the item can be a feature for the migration-toolkit, therefore we might look into it. We will have to decide whether it will be default behavior or just behind some switch option.

**Comment by subhamAgarwal-cloud** [comment]
Hi, @IvanKiral  by when can we hear on the implementation of Switch or the new feature? Any expected timeline?

**Comment by Enngage** [comment]
Hi @subhamAgarwal-cloud, 

I'll look at implementing it this week. If all goes well, I'll release an update by the end of the week.

**Comment by nkooman-bzs** [comment]
This is similar to #10

**Comment by Enngage** [comment]
Merged to main. I expect to release Tomorrow.

**Comment by Enngage** [comment]
Relased in `2.3.0`
