### ISSUE TITLE
Rate exceeded and not found error codes are the same

### ISSUE THREAD

**Issue by nkooman-bzs** [kontent-ai/kontent-ai-migration-toolkit#20]
### Brief bug description

The two constants defined in the HTTP utils have the same value, resulting in the second pattern to never be hit.
https://github.com/kontent-ai/kontent-ai-migration-toolkit/blob/446575ebd7950f33bd8ecf06b6ec924bcc77e289/lib/core/utils/http.utils.ts#L5-L6

### Repro steps

N/A Inconsistent logic in code.

### Expected behavior

A clear distinction between "rate exceeded" and "not found" error codes in the pattern handling

### Test environment

N/A

### Additional context

N/A

### Screenshots

N/A

**Comment by Enngage** [comment]
Hi @nkooman-bzs,

Nice catch :) I've forgotten to remove this condition for handling `notFoundErrorCode`. It is not necessary due to the more general condition right below that:

```
// if error code is set, do not retry the request
.when( (errorCode) => errorCode >= 0,() => false )
 ```
