### ISSUE TITLE
Running into API rate limits

### ISSUE THREAD

**Issue by nkooman-bzs** [kontent-ai/kontent-ai-migration-toolkit#22]
### Brief bug description

While running a script that utilizes migration toolkit, I am running into API rate limit errors when `importAsync` is invoked.
I've tried increasing the backoff and attempts. I've also removed jitter to ensure a larger timeout.
Observing the issue is difficult since it's intermittent. When I do see it pop up, it feels like the HTTP service is not abiding by the retry strategy I pass to the `importManager`. I believe it's only happening when the import context is being gathered, but I cannot fully confirm.
It might be possible that the issue lies in the [core SDK](https://github.com/kontent-ai/core-sdk-js/tree/master). However, this seems unlikely.

Strategy passed to `importManager`:
```js
retryStrategy: {
  canRetryError: defaultRetryStrategy.canRetryError,
  maxAttempts: 6,
  deltaBackoffMs: 3000,
},
```

### Repro steps

1. Import a large amount of items (500-1000 items)
2. See that API rate limit errors appear

### Expected behavior

What is the correct behavior?

With maximum backoff being over a minute, I expect that it would be impossible to hit the API rate limit since it's 400 requests a minute.

### Test environment

From `package.json`
```
"@kontent-ai/core-sdk": "^10.8.0",
"@kontent-ai/data-ops": "^1.6.1",
"@kontent-ai/delivery-sdk": "^15.0.0",
"@kontent-ai/management-sdk": "^7.2.0",
"@kontent-ai/migration-toolkit": "^1.5.1",
```

### Additional context

Sorry for the vagueness, but I am unable to concretely replicate this issue.
I receive the generic rate limitation error when it occurs.
`"API rate limit exceeded. Please retry your request later. See https://kontent.ai/learn/mapi-v2-rate-limit for details."`

### Screenshots

N/A

**Comment by Enngage** [comment]
Hey @nkooman-bzs,

The retry strategy seems to be working well when testing it on my end. Is it possible that there is some additional traffic on the project / environment where the migration is running? If so, it might be that even the `6` retry attempts are not enough.

I've tried importing `1000` items using a script like:

```
    const environmentId = x;
    const apiKey = z
    const log = getDefaultLogger();

    const client = createManagementClient({
        apiKey: apiKey,
        environmentId: environmentId
    });

    const exportItems: SourceExportItem[] = [];
    for (let i = 0; i < 1000; i++) {
        exportItems.push({ itemCodename: `sample_item_${i}`, languageCodename: 'en' });
    }

    for (const exportItem of exportItems) {
        const contentItem = await client
            .upsertContentItem()
            .byItemCodename(`sample_item_${exportItem.itemCodename}`)
            .withData({
                name: `Sample item ${exportItem.itemCodename}`,
                type: {
                    codename: 'test'
                }
            })
            .toPromise();

        await client
            .upsertLanguageVariant()
            .byItemId(contentItem.data.id)
            .byLanguageCodename('en')
            .withData((builder) => {
                return {
                    elements: [
                        builder.textElement({
                            element: {
                                codename: 'text'
                            },
                            value: `Sample text ${exportItem.itemCodename}`
                        })
                    ]
                };
            })
            .toPromise();

        await client.publishLanguageVariant().byItemId(contentItem.data.id).byLanguageCodename('en').withoutData().toPromise();

        console.log('Item created', exportItem.itemCodename);
    }

    const exportData = await exportAsync({
        logger: logger,
        environmentId: environmentId,
        apiKey: apiKey,
        exportItems: exportItems
    });

    await storeAsync({
        data: exportData,
        filename: 'data.zip'
    });

     await importAsync({
        logger: log,
        data: data,
        environmentId: environmentId,
        apiKey: apiKey,
        createReportFile: true
    });
```
    
Are you able to reproduce it using this script (w/o modifications)?

**Comment by nkooman-bzs** [comment]
@Enngage thanks for the reply.

I have stopped seeing the error since writing this issue. You may be write that there's some additional traffic in the environment.
We've moved to a cloned environment so that we can avoid possible issues with usage from other sources. I will re-open this issue if the problem reappears.
