### ISSUE TITLE
Importing the sample assets-export.zip results in an error

### ISSUE THREAD

**Issue by mberry1989** [kontent-ai/kontent-ai-migration-toolkit#4]
### Brief bug description

Running the command:

`kontent-ai-migration-toolkit --action=import --managementApiKey=<redacted_for_GH_Issue>--itemsFilename=assets-export.zip --format=json
`
against the downloaded sample data results in the error:

`Error:  Corrupted zip: missing 16 bytes.`

### Repro steps

1. Setup the target content models in Kontent.ai for Actor and Movie
2. Download the _assets-export.zip_ from the sample folder
3. Run the import command targeting the downloaded .zip

**Comment by Enngage** [comment]
Should now be working as expected.
